language: node_js
sudo: required
services:
  - docker
node_js:
  - "lts/boron"
jobs:
  include:
    - stage: test
      script:
        - npm install
        - npm run test:coverage
    - stage: package
      script:
        - docker build -t tsukhu/express-microservice .
