---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "express-microservice"
  namespace: "default"
  labels:
    app: "express-microservice"
    version: "1.0.0"    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "express-microservice"
      version: "1.0.0"
  template:
    metadata:
      labels:
        app: "express-microservice"
        version: "1.0.0"
    spec:
      serviceAccount: "default"
      containers:
      - env:
        - name: APP_ID
          valueFrom:
            configMapKeyRef:
              key: app-id
              name: "express-microservice"
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              key: log-level
              name: "express-microservice"
        - name: REQUEST_LIMIT
          valueFrom:
            configMapKeyRef:
              key: request-limit
              name: "express-microservice"
        - name: SESSION_SECRET
          valueFrom:
            configMapKeyRef:
              key: session-secret
              name: "express-microservice"
        - name: SWAGGER_API_DOCS_ROOT
          valueFrom:
            configMapKeyRef:
              key: swagger-api-docs-root
              name: "express-microservice"
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: app-port
              name: "express-microservice"
        - name: LOG_DIRECTORY
          valueFrom:
            configMapKeyRef:
              key: log-directory
              name: "express-microservice"                     
        image: "tsukhu/express-microservice:latest"
        imagePullPolicy: Never
        name: "express-microservice"
        ports:
        - containerPort: 3000
          protocol: TCP
      restartPolicy: Always
