---
apiVersion: v1
kind: Service
metadata:
  name: "express-microservice"
  namespace: "default"
  labels:
    app: "express-microservice"
    version: "1.0.0"
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: "express-microservice"
    version: "1.0.0"
    
